name: mksc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy<2.0
  - pandas
  - matplotlib
  - scipy
  - statsmodels
  - scikit-learn
  - lightgbm
  - joblib
  - numba
  - jupyterlab
  - ipykernel
  - nbconvert
  - pytest
  - ruff
  - pip
  - pip:
      - econml==0.15.0
      - scienceplots==2.2.0
      - cloudpickle==3.0.0
      - shap==0.43.0
      - sparse==0.15.4
      - yellowbrick>=1.5
      - nbmake
